from BeautifulSoup import BeautifulSoup

def test(text):
    soup = BeautifulSoup(text)
    for tag in soup.findAll():
        if tag.name != 'li' and len(tag.contents) >= 1 and len(tag.text.split())<10:
            print tag
            print
            break
#     print
#     print
#     print
    
texts = [
    "<div><div><strong>Overview:</strong><br /><br />Therapy Management Corporation is an industry leader in therapy services and operates in multiple states.<br /><br />At TMC, we believe the foundation for success starts with our employees. We approach each day at TMC with enthusiasm, dedication and creativity. Our team members take pride in representing the Committed to Service Excellence philosophy every day. TMC is dedicated to providing stability, exceptional clinical education, job satisfaction, as well as, opportunities for career and professional advancement. We offer our employee s competitive compensation, a diverse benefit package and so much more!<br /><br />TMC has employment opportunities in Skilled Nursing, Assisted Living, Independent Living Facilities and Outpatient Clinics. Our Rehab teams are comprised of highly skilled, dynamic, passionate professionals who promote the most positive outcome for each of our patients.<br /><br />We are confident that our history of providing therapy services with uncompromised quality and our Commitment to Service Excellence , as well as opportunities for personal and professional growth make us the employer of choice in the therapy services industry.</div></div><br />",
    "<p><strong>Experience we are looking for </strong><br /> High school diploma, 1 yr. relevant work experience or equivalent combination of education and relevant work experience.<br /> 1 yr. prestige product lines retail experience.<br /> Demonstrates significant competency in sales, products and service.<br /> Strong communication skills.<br /> Ability to troubleshoot.<br /> Ability to work independently and as part of a team.<br /> Ability to lead a team.<br /> Ability to build and maintain strong customer relationships. </p><p><br /><strong>Other</strong><br /> On a regular basis, requires the ability to stand, bend and lift 50 lb. merchandise for a full scheduled shift.</p><p> A Demonstrator s license is required in Nevada</p><p> A Cosmetology or Estheticians license is required in Maine </p> ",
    "<p>The Prestige Beauty Advisor is responsible for maximizing sales through assisting guests in the selection and purchase of prestige merchandise, while following all company policies and procedures. <br /><strong>Use your skills, experience, &amp; talents to be part of something BEAUTIFUL!</strong> As a Prestige Beauty Advisor you will perform the following essential functions <br /> Acknowledge and greet all guests and offers friendly, prompt and courteous service.<br /> Inform guests of current promotions, events, and services within the store.<br /> Responsible for meeting or exceeding individual sales and productivity goals. <br /> Responsible for presenting an image at all times that reflects the knowledge of the prestige cosmetic lines sold at ULTA.<br /> Routinely does makeup applications, skincare analysis, and product demonstrations with guests.<br /> Book appointments for scheduled special events.<br /> Ensure that all testers within Prestige area are continuously in stock and maintained in compliance with the hygiene standards.<br /> Ensure stock is kept full at all times within the prestige categories.<br /> Ensure all resets and planograms are executed as directed.<br /> Ensure makeover stations adhere to company standards at all times.<br /> Maintain company visual merchandising standards.<br /> Maintain standards of cleanliness and organization within the prestige area and ULTA color library.</p>",
    "<ul><li>$1,500 SIGN ON BONUS</li> <li>Affordable Lease to Own Program.</li> <li>No Down Payment or Balloon Payment</li> <li>No Credit Check Required</li> <li>Excellent Pay Packages, Up to 80%</li> <li>Base Pay Package 75% of Line haul, 100% fuel surcharge</li> <li>2% additional pay package for Driver Touch Freight</li> <li>3% additional Load Assignment Bonus</li> <li>Direct Deposit options/weekly settlements</li> <li>Safety bonuses</li> <li>Comdata Cards provided</li> <li>Elogs, Qualcomm, and In cab scanning</li> </ul> <p><br /><strong>To qualify you must have:</strong></p> <ul> <strong>Minimum of 1 year of recent Class A CDL experience</strong> <strong>Good Driving record required</strong> <strong>25 Yrs old</strong> </ul> ",
    "<span>If you need a truck, we offer a program where over time you can become the owner of a truck with Zero Down and No Balloon Payment at the end of the contract.</span> ",
    "<p><span><strong>As a Professional OTR O/O Driver, What would YOU like to Accomplish?</strong> <br /></span><br />If you are a professional looking for something more from your driving experience, we need to talk! <br /><br />RT&amp;T knows that we make money when ",
    "Want To Earn More? Want Great Benefits and Consistent Home Time?\nLet Us Match Your Application Information to Trucking Companies That are Hiring Drivers Now!",
    "<span><strong>The</strong> KOCH DEDICATED DIVISION</span><p> Class A Drivers Needed Immediately for Flatbed Dedicated Openings </p><span>NEW!<br />$5000 Orientation Completion Bonus</span><span> Yearly earnings of between $55,000 - $63,000</span><span> 2500 - 3000 miles per week </span><span> Late Model Equipment Great benefits</span><span> $30/per stop, $25 tarp/load</span><span> VIP Platinum orientation (Flight to Orientation, upscale lodging, all meals provided)</span><span>Requirements: 1 year Class A CDL experience required, 6 months Flatbed experience required. Minimum23 years old</span><span>www. Koch Trucking.jobs</span>",
]

for text in texts:
    test(text)