# DB Details
MONGODB_HOST = "localhost"
MONGODB_PORT = 27017
MONGODB_NAME = "timesheets"

# Collections
SHEETS_COLLECTION = "sheets"
LOGS_COLLECTION = "work_logs"
ACCESS_TOKENS = "access_tokens"

# Fields
SPREADSHEET_ID = "spreadsheet_id"
MONTH = "month"
YEAR = "year"
DATE = "date"
USER_SHEET_INDEX = "sheet_index"
USER_LEAVES = "leaves"
LEAVE_PURPOSE = "purpose"
LEAVE_APPROVED_STATUS = "approved"
LEAVE_TYPE = "type"
WORK_FROM_HOME = "work_from_home"
WORK_DETAILS = "work_details"
SPECIAL_WORKING_FLAG = "is_special_working"
TASK_DETAILS = "task_details"
TASK_FIELD = "task"
WORKING_HOURS = "working_hours"
WORKING_ORDER_FIELD = "working_order"
JIRA_TICKET_NUMBER = "jira_ticket_number"
DIALOG_FLOW_SESSION_ID = "dialogflow_session_id"
TASK_TYPE_FIELD = "task_type"

# WRS_FIELDS
WRS_NAME = "full_name"
WRS_EMAIL = "email"
WRS_ID = "id"
WRS_UUID = "uuid"
WRS_USER_NAME = "user_name"
WRS_USER_ID = "user_id"
WRS_USER_UUID = "user_uuid"
WRS_PROJECT_ID = "project_id"
WRS_PROJECT_UUID = "project_uuid"
WRS_PROJECT_NAME = "project_name"
WRS_EMPLOYEE_ID = "employee_id"
WRS_USER_INFO = "user_info"
WRS_ACCESS_TOKEN = "wrs_access_token"
WRS_EMPLOYEE_USER_ID = "employee_id"
WRS_EMPLOYEE_USER_UUID = "employee_uuid"
WRS_EMPLOYEE_USER_NAME = "employee_name"
WRS_EMPLOYEE_EMAIL = "employee_email"